const SET_POSTS = 'SET_POSTS';
const LOAD_POSTS = "LOAD_POSTS";
const SET_SELECTED_POST = "SET_SELECTED_POST";
const LOAD_SELECTED_POST = "LOAD_SELECTED_POST";
const SET_PER_PAGE = 'SET_PER_PAGE';
const SET_TOTAL = 'SET_TOTAL';
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
const LOAD_SEARCH_POSTS = 'LOAD_SEARCH_POSTS';
const SET_SORT_FIELD = 'SET_SORT_FIELD'

export {
    SET_POSTS,
    LOAD_POSTS,
    SET_SELECTED_POST,
    LOAD_SELECTED_POST,
    SET_PER_PAGE,
    SET_TOTAL,
    SET_CURRENT_PAGE,
    LOAD_SEARCH_POSTS,
    SET_SORT_FIELD
}